# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, unique=True, verbose_name='标题')),
                ('content', models.CharField(max_length=255, unique=True, verbose_name='内容')),
                ('keywords', models.CharField(max_length=20, unique=True, verbose_name='关键字')),
                ('describe', models.CharField(max_length=30, unique=True, verbose_name='描述')),
            ],
            options={
                'db_table': 'text_upload',
            },
        ),
    ]
